### ISSUE TITLE
Add LuaCheck (with GitHub workflow)

### ISSUE THREAD

**Issue by Panquesito7** [appgurueu/modlib#11]

**Comment by appgurueu** [comment]
I'm afraid this isn't really possible since I use environments heavily. Most modules have roughly the following structure:

```lua
local ... = ... -- "imports"
local _ENV = {}
setfenv(1, _ENV)
...
return _ENV
```

I'm not aware of a way to tell LuaCheck that this code runs in a different environment. I'll probably write my own linter or patch LuaCheck eventually, but until then this is not a priority.
