### ISSUE TITLE
Calling modlib.matrix4.rotation() with nil induces a segfault.

### ISSUE THREAD

**Issue by FatalistError** [appgurueu/modlib#13]
![Screenshot 2023-08-25 160058](https://github.com/appgurueu/modlib/assets/58855799/296afb01-8c82-4e1e-9d07-065e1104d14d)

I have no idea how this is set up, but I accidentally passed a nil value (wrong index) to modlib.matrix4.rotation(), and it seems to cause segfaults. This could potentially be due to the weird environment setup that modlib uses- no idea. 

assert() needed.

**Comment by appgurueu** [comment]
Looks like an engine issue. "Attempt to index a nil value" shouldn't cause a segfault. If it causes a segfault here, where else does it cause one? I vaguely remember seeing this issue in other places too. This should be fixed at an engine level; mod level workarounds would clutter the codebase for no significant benefit (it is obvious that the parameter isn't optional).
I prefer not to sprinkle my code with `assert`s - that defeats the point of using Lua (of course this doesn't apply to readers, which need to be strict in what they accept, since we can't assume that their input is "safe").

Considering that there is a proper stack trace in the terminal / `debug.txt`, I don't even really see an issue with this as a mod developer. Of course it's pretty bad from a player perspective.

**Comment by FatalistError** [comment]
> Looks like an engine issue. "Attempt to index a nil value" shouldn't cause a segfault. If it causes a segfault here, where else does it cause one? I vaguely remember seeing this issue in other places too. This should be fixed at an engine level; mod level workarounds would clutter the codebase for no significant benefit (it is obvious that the parameter isn't optional). I prefer not to sprinkle my code with `assert`s - that defeats the point of using Lua (of course this doesn't apply to readers, which need to be strict in what they accept, since we can't assume that their input is "safe").
> 
> Considering that there is a proper stack trace in the terminal / `debug.txt`, I don't even really see an issue with this as a mod developer. Of course it's pretty bad from a player perspective.

I don't know why you closed this, but it causes a segfault EVERYWHERE in your modules, if you try to index a nil value it always induces a segfault. You need to assert for values everywhere since you somehow managed to make MT cry

**Comment by FatalistError** [comment]
"I don't see an issue with it as a developer" if players can't provide error messages, then how do they know what went wrong. C'mon app

**Comment by appgurueu** [comment]
> I don't know why you closed this, but it causes a segfault EVERYWHERE in your modules, if you try to index a nil value it always induces a segfault. You need to assert for values everywhere since you somehow managed to make MT cry

No, MT needs to be fixed. This is an engine issue. I'm not manually messing up my code to partially work around an engine issue.
