### ISSUE TITLE
Assertion error trying to write to Readme.md at server startup

### ISSUE THREAD

**Issue by ronoaldo** [appgurueu/modlib#5]
At least it's what I figured out by reading the logs... Were not happening recently but started today:

![Screenshot_20210919_235806](https://user-images.githubusercontent.com/564649/133953255-c01ed861-c4cf-4495-8f85-45cdf4c00ea1.png)

**Comment by appgurueu** [comment]
Kinda looks like a mod security issue to me. For now, updating character_anim should fix it for you, as I have updated the Readme (so it shouldn't have to write it anymore).

**Comment by ronoaldo** [comment]
Thanks! I'll check it out. For now I have disabled the mod. Next server update I'll test it again.

**Comment by appgurueu** [comment]
Can't reproduce. With mod security enabled and neither `modlib` nor `character_anim` in `secure.trusted_mods` everything is fine; the configuration section in the Readme is overwritten without any error, as is expected since Minetest allows writes to the mod directory at load time.

If you can somehow still reproduce this, please comment and I will reopen the issue.

**Comment by ronoaldo** [comment]
This particular issue has not happened anymore.

Personally, I would consider development-time changes to README fine, but run-time changes not fine; but I'm fine with that.

**Comment by appgurueu** [comment]
> Personally, I would consider development-time changes to README fine, but run-time changes not fine; but I'm fine with that.

Definitely agreed that this is somewhat dirty. Note that it only touches the Readme if the conf section is out of date though.
