### ISSUE TITLE
Can't convert B3Ds from TFL S7 Stock Modpack

### ISSUE THREAD

**Issue by Montandalar** [appgurueu/modlib#9]
## Background

I am working on trying to convert B3Ds included in older train mods back to some format Blender can import properly. At the moment my focus is on the   [TfL S7 Stock Modpack](https://notabug.org/advtrains_supplemental/tfl_s7_stock_modpack).

I hoping to fix the shading issues on one side of those wagons which I think are from flipped normals.  I was also hoping to make a new .blend file.  I wanted to use modlib's B3D loader and gltf exporter to try to convert the models, but the process fails to produce readable output.

## Steps
I appended the following to the end of tfl_s7stock_modpack's init.lua based on the docs example:
```lua
minetest.register_chatcommand("b3d2gltf", {
    description = "Convert b3d models to gltf",
    privs = {server=true},
    func = function(name, param)
        local b3d = modlib.b3d
        local modpath = minetest.get_modpath("tfl_s7stock_modpack")
        local dir_path = modpath .. "/models"
        local out_dir_path = modpath .. "/gltf"
        for _, filename in ipairs(minetest.get_dir_list(dir_path, false --[[only files]])) do
            -- First read the B3D
            minetest.log("warning", filename)
            local in_file = assert(io.open(dir_path .. "/" .. filename, "rb"))
            local model = assert(b3d.read(in_file))
            in_file:close()
            -- Then write the glTF
            local out_file = io.open(out_dir_path .. "/" .. filename .. ".gltf", "wb")
            model:write_gltf(out_file)
            out_file:close()
        end
    end
})
```
as well as adding modlib to the mod's `depends.txt` (haven't gotten around to converting to mod.conf yet..)

However upon running the chat command, lead this leads to the stack trace:
```
2023-03-14 16:43:37: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'tfl_s7stock_modpack' in callback on_chat_message(): /home/blockhead/.minetest/mods/modlib/b3d.lua:784: attempt to get length of a nil value
2023-03-14 16:43:37: ERROR[Main]: stack traceback:
2023-03-14 16:43:37: ERROR[Main]: 	/home/blockhead/.minetest/mods/modlib/b3d.lua:784: in function 'func'
2023-03-14 16:43:37: ERROR[Main]: 	/home/blockhead/.minetest/mods/modlib/b3d.lua:625: in function 'add_accessor'
2023-03-14 16:43:37: ERROR[Main]: 	/home/blockhead/.minetest/mods/modlib/b3d.lua:781: in function 'add_mesh'
2023-03-14 16:43:37: ERROR[Main]: 	/home/blockhead/.minetest/mods/modlib/b3d.lua:952: in function 'add_node'
2023-03-14 16:43:37: ERROR[Main]: 	/home/blockhead/.minetest/mods/modlib/b3d.lua:988: in function 'to_gltf'
2023-03-14 16:43:37: ERROR[Main]: 	/home/blockhead/.minetest/mods/modlib/b3d.lua:1030: in function 'write_gltf'
2023-03-14 16:43:37: ERROR[Main]: 	/home/blockhead/.minetest/mods/tfl_s7stock_modpack/init.lua:212: in function 'func'
2023-03-14 16:43:37: ERROR[Main]: 	/usr/local/share/minetest/builtin/game/chat.lua:79: in function </usr/local/share/minetest/builtin/game/chat.lua:52>
2023-03-14 16:43:37: ERROR[Main]: 	/usr/local/share/minetest/builtin/game/register.lua:446: in function </usr/local/share/minetest/builtin/game/register.lua:432>
```

## Debugging
It does not matter which model is attempted for conversion, the same underlying issue exists in both b3d files in the mod. Here are my changes to modlib to try to debug the scenario:
```diff
diff --git a/b3d.lua b/b3d.lua
index c4d2d47..04d3619 100644
--- a/b3d.lua
+++ b/b3d.lua
@@ -10,6 +10,7 @@ local write_int, write_uint, write_single = modlib.binary.write_int, modlib.bina
 
 local fround = modlib.math.fround
 
+local dbg = dbg
 -- Set environment
 local _ENV = {}
 setfenv(1, _ENV)
@@ -781,7 +782,10 @@ do
                                        attributes[("JOINTS_%d"):format(set_id)] = add_accessor("VEC4", "unsigned_short", false, function(write_byte)
                                                for vertex_id in ipairs(mesh.vertices) do
                                                        for i = set_start, set_start + 3 do
-                                                               assert(#normalized_weights[vertex_id] == #joint_ids[vertex_id])
+                                                               dbg()
+                                                               --local nnormw = #normalized_weights[vertex_id]
+                                                               --local njid = #joint_ids[vertex_id]
+                                                               --assert(nnormw == njid)
                                                                local id = (joint_ids[vertex_id] or {})[i] or 0
                                                                local weight = (normalized_weights[vertex_id] or {})[i] or 0
                                                                if weight == 0 then
```
Removing the assertion, or even commenting out the whole block will remove the stack trace problem, but this only hides the symptoms. Once the converter "succeeds", the files are unreadable by Blender. In any case, the table indices do *not* match up between these three tables, as evidenced by this trimmed down version of my debugging session:
```
dbg> dbg.pp(normalized_weights[vertex_id])
nil

#No entries 1-5089, 5093-11149
dbg> dbg.pp(normalized_weights)
{
    [5090] = {
        1
    },
    [5092] = {
        1
    },
    [11150] = {
        1
    },
    [11151] = {
        1
    },
...
    [12200] = {
    1
    }
}


dbg> dbg.pp(joint_ids)
{
    [5090] = {
        7
    },
    [5092] = {
        7
    },
    [11150] = {
        4
    },
    [12200] = {
        8
    }
}

dbg> dbg.pp(#mesh.vertices)
12202
```

Now I take it that the lack of data is supposed to be compensated-for by the `or 0` on the end of the following assignments, but nevertheless the `#` operator will never work properly in tables that don't actually start at 1.

## The crux of the problem
Are my models malformed? Can/will modlib try to work around/repair them if they are? If not, what will it take for a fix to happen?

**Comment by appgurueu** [comment]
Thanks for the report. I've tested this conversion only with Sam and PaleoTest models, so I'm always happy if I get reports of models where it doesn't work (yet)!

Considering Minetest can load your models, I'd assume that this is a modlib bug (or that modlib should at least attempt to be lax enough to repair this). If I figure out that this is indeed a model issue, I'll make sure to add proper assertions that throw usable errors. Will look into it.

**Comment by appgurueu** [comment]
There are two underlying issues:

1. Your models do not provide textures / brushes. `modlib` does not handle this correctly; it produces an empty material list and sets `-1` as the material ID (it should produce a `nil` brush list and set `nil` as the material ID, such that both don't appear in the glTF JSON). I'm contemplating whether `modlib` should be lax here, automatically adding a "default" brush if it detects UVs.
2. More problematic: Your models have vertices that are not affected by any bones. This is responsible for the crash you're seeing: `assert(#normalized_weights[vertex_id] == #joint_ids[vertex_id])` implicitly expects the vertex to be influenced by at least one joint - otherwise `normalized_weights` and `joint_ids` will be `nil`, triggering the error you are seeing (this is unrelated to the usage of the `#` operator, which is correct here). I am not sure how to represent this in glTF (if it can be represented at all) since it seems I *must* provide weights for all vertices, but I *may not* provided all-zero weights (see https://github.com/KhronosGroup/glTF/issues/1929). I've raised a new issue: https://github.com/KhronosGroup/glTF/issues/2269.

I've ~~got a fix locally~~ pushed a fix (https://github.com/appgurueu/modlib/commit/2425862045e2bff6ccf48eb17fed6a2bebd1143f) for (1). After applying the fix (and a second fix: removing the assertion or using `or {}` on both sides), glTF validator still complains (about the vertices with zero bone weights), but Blender loads the model; however all non-animated geometry is missing.

I'm not sure how I'd tackle (2). Current workarounds I see would be (a) introducing no-op bones (ugly, esp. if you want to edit the model afterwards) or (b) trying to split the mesh up into animated and non-animated primitives (potentially not general enough, since it wouldn't support not animating single vertices, which b3d technically supports).

---

Side note: In `dbg`, you shouldn't have to wrap your expressions `dbg.pp` - it should be implicit if you just enter an expression.

**Comment by appgurueu** [comment]
After discussing this with Auri, I think I'll go with adding a neutral bone like Blender: https://github.com/KhronosGroup/glTF-Blender-IO/pull/1552/

**Comment by appgurueu** [comment]
Fixed in https://github.com/appgurueu/modlib/commit/fc0585e86ce932ca592afb04f126c30de5e8d410 and https://github.com/appgurueu/modlib/commit/88fec749f54c0e506a6ab0fd94340e22555ea502.

The second commit (normalizing normals) is likely related to your issue:

> [I'm] hoping to fix the shading issues on one side of those wagons which I think are from flipped normals.

While converting the models, I found out that they use normals with a length of around 10-11 (!) rather than a normalized length of 1.

`modlib` now converts them just fine; the normal issues are apparent in Blender:

![Bildschirmfoto vom 2023-04-02 14-58-06](https://user-images.githubusercontent.com/34514239/229354312-149e0dcf-88c3-46a9-87ac-55ae4abb8519.png)

Thanks for the report!
